import "D3DCommon.idl";
import "d3d11_4.idl";
import "d3d11sdklayers.idl";
import "dxgi1_6.idl";

[uuid(12345678-1234-1234-1234-123456789ABC)]
library RenderToyCOM
{
	// Direct3D 11
	interface ID3D11Debug;
	interface ID3D11Device5;
	interface ID3D11DeviceContext4;
	enum D3D11_BIND_FLAG;
	enum D3D11_CLEAR_FLAG;
	enum D3D11_COPY_FLAGS;
	enum D3D11_CPU_ACCESS_FLAG;
	enum D3D11_MAP_FLAG;
	enum D3D11_RESOURCE_MISC_FLAG;
	// DXGI
	interface IDXGIAdapter4;
	interface IDXGIFactory6;
	interface IDXGIOutput6;
}